name: yempay
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # مكتبة شبكات الاتصال HTTP
  http: ^1.2.0

  # الأيقونات الرسمية لنظام iOS
  cupertino_icons: ^1.0.8

  # مكتبات التوطين واللغات الرسمية
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  #generate: true # <-- هذا السطر هو الأساس لتوليد package:flutter_gen
  uses-material-design: true
  
  # تفعيل التوليد التلقائي لملفات الترجمة (AppLocalizations)
 